import Head from 'next/head';
import Cart from 'react-shoppingcart';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    content="Generated by create next app"
                    name="description"
                />
                <meta
                    content="width=device-width, initial-scale=1"
                    name="viewport"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <main className="container">
                <Cart />
            </main>
        </>
    );
}
